# Generated by Django 5.2.6 on 2025-09-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='lunch',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='plan',
            field=models.JSONField(default=dict),
        ),
    ]
