# Generated by Django 5.2.6 on 2025-09-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='daily_calorie_goal',
        ),
        migrations.AddField(
            model_name='user',
            name='additional_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dietary_preference',
            field=models.CharField(choices=[('classic', 'Clásico'), ('vegetarian', 'Vegetariano'), ('vegan', 'Vegano'), ('pescetarian', 'Pescetariano')], default='classic', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='objective',
            field=models.CharField(blank=True, choices=[('lose', 'Perder peso'), ('maintain', 'Mantener peso'), ('gain', 'Aumentar peso')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', '0-2'), ('moderate', '3-5'), ('active', '6+')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
