# Generated by Django 5.2.6 on 2025-09-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_daily_calorie_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calories_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='carbs_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fat_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='goals_method',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('ai', 'IA')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='protein_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
