# Generated by Django 5.2.6 on 2025-09-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_calories_goal_user_carbs_goal_user_fat_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='water_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='water_method',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('ai', 'IA')], max_length=10, null=True),
        ),
    ]
